version: 2

models:

  - name: stg_orders
    description: "Cleaned order data"
    columns:

      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id

      - name: vehicle_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_vehicles')
                field: vehicle_id

      - name: driver_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_drivers')
                field: driver_id

      - name: route_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_routes')
                field: route_id

  - name: stg_vehicles
    description: "Cleaned vehicle data"
    columns:

      - name: vehicle_id
        tests:
          - not_null
          - unique

  - name: stg_customers
    description: "Cleaned customer data"
    columns:

      - name: customer_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

  - name: stg_drivers
    description: "Cleaned driver data"
    columns:

      - name: driver_id
        tests:
          - not_null
          - unique

  - name: stg_routes
    description: "Cleaned route data"
    columns:

      - name: route_id
        tests:
          - not_null
          - unique